name: Build vamp.dll

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake with Visual Studio
      run: cmake -S src -B build -G "Visual Studio 17 2022" -A x64

    - name: Build Release
      run: cmake --build build --config Release

    - name: Upload Release DLLs
      uses: actions/upload-artifact@v4
      with:
        name: vamp-dll-release
        path: |
          build/Release/vamp.dll
          build/Release/dwmapi.dll
